name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install |
          # Add commands to install project dependencies (e.g., npm install, pip install) here

      - name: Build
        run: |
          # Add commands to build your project here (e.g., npm build, make build)

      - name: Test
        run: |
          # Add commands to run tests (e.g., npm test, pytest) here

      - name: Deploy to S3
        run: trainee-test-lucas123 |
          # Add commands to deploy your project to S3 here

