name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.ACCESS }}
          aws configure set aws_secret_access_key ${{ secrets.SECRET }}

      - name: Sync Files to S3 Bucket
        run: |
          aws s3 cp ./index.html s3://trainee-test-lucas123/
          aws s3 cp ./game.js s3://trainee-test-lucas123/
        working-directory: ./
